events {}

http {
    upstream backend_servers {
        server backend-service:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}
